### ISSUE TITLE
有个疑问

### ISSUE THREAD

**Issue by ronalfei** [gansidui/gotcp#10]
closechan里的消息, 是在什么地方放进去的?
而且 read, handle, 和write三个loop都会去接收里面的消息, 然后执行关闭操作.
那其余两个没收到, 会因为close(chan)而关闭其余的goroutine吗?

**Comment by gansidui** [comment]
close(chan)的时候，相当于广播一个通知，其他所有等待这个channel的地方都将返回，所以closechan只用关闭就可以了，向closechan插入数据是达不到广播的效果的（因为只会有一处地方会返回）。
