### ISSUE TITLE
你这支持异步写数据么？

### ISSUE THREAD

**Issue by whidbey** [gansidui/gotcp#12]
客户端链接会话保存到redis，根据情况单独发送数据。
示例都是echo或者telnet的场景实际上很少

**Comment by gansidui** [comment]
你说的这种是业务层的逻辑，都是可以实现的

**Comment by whidbey** [comment]
目前测试稳定没？目前golang的tcp框架你这写的不错。
如果需要单独发送，是否这样。
把Onconnect时，把c *gotcp.Conn 序列化到redis。
需要给某个客户端发送tcp包，直接取出来序列化为*gotcp.Conn，AsyncWritePacket() 对么？

**Comment by gansidui** [comment]
只是一个简单的封装，所以暂时没发现稳定性的问题。
对于你说的业务逻辑可以这样：每个客户端肯定是有一个业务标识的，姑且定位UIN，用UIN来映射到conn（比如 map[UIN]*conn）即可

**Comment by whidbey** [comment]
好的，thx，看到你的亮点是单机支持几十万个连接的特性不错。

**Comment by whidbey** [comment]
期待封装的更牛
