### ISSUE TITLE
建议以树形结构维护客户端，新增连接池,多协议,增加事件回调等

### ISSUE THREAD

**Issue by lchjczw** [gansidui/gotcp#13]
server-->db_pool_conn
          -->client_conns
          -->add_port1<--->protocol（增加监听端口）
          -->add_port2<--->protocol（tcp、udp、其他协议）

event--->conect
event--->close
event--->task(耗时任务)
event--->recieve
我觉得可以按照计划，一步步实现这些功能，这样就是一个强大的tcp框架了
以后再引入model、rpc等

**Comment by gansidui** [comment]
多谢关注，后续应该会增加一些新的功能，同时欢迎提交代码

**Comment by lchjczw** [comment]
简单加了个连接池，太简单了

**Comment by gansidui** [comment]
server不需要连接池吧，client才考虑

**Comment by lchjczw** [comment]
连接池这个是考虑到的场景是：服务端需要给某一个客户端推送数据，比如说，需要给15号客户端发送数据，这种情况下，我如何找到15号客户端

**Comment by gansidui** [comment]
在内存中映射 uin 到 conn， 比如：map[int64]*conn，直接用map[15]就可以找到15号客户端的socket，你说的是不是这种情况？ 可是这个并不是连接池

**Comment by lchjczw** [comment]
我的意思就是服务端需要去维护一个客户端的列表，或者map，可以随时给客户端发送数据，我的是给map[client_ip]*conn,这样外部可以更好通过ip找到conn

**Comment by gansidui** [comment]
明白你的意思了， 不过维护客户端列表这种事情交给业务层去做比较好。
用map[client_ip]*conn这种我想不到有哪种业务模型需要这样保存，更多情况下都是有账号体系的，在登录包里面带上客户端标识UIN（比如QQ账号），服务器保存 map[UIN]*conn。

**Comment by whidbey** [comment]
框架封装这个也是可以的。目前就是用了map

**Comment by zhaoyuexian** [comment]
想要上下文 自己在OnConnect的时候加就Ok了，而且有的是有登录的，只有登录完成的才加入，所以还是业务去做吧

**Comment by businiaowyf** [comment]
lchjczw需要的是在线状态吧，可以方便push消息， 我觉得这些还是放在业务层去做
