### ISSUE TITLE
请问如何优雅地使用gotcp框架做客户端？

### ISSUE THREAD

**Issue by businiaowyf** [gansidui/gotcp#15]
我想用该框架开发一个后台系统，收到包之后顺序转发给后面的server1， 然后等待后端server1回包再请求server2，server2回包再给前端回包。
我的做法是在OnMessage里面创建goroutine使用tcp短连接发包后端server， 然后等待后端server回包。也就是SendAndRecv的过程，但是这样每个请求都要创建连接开销有点大。
另外想到的一种做法是参考异步网络框架，将连接后端server的socket也放到主线程中readloop，但是这样的话又需要维护一个状态机，不如协程做法复杂性低。请问楼主是怎么做的？

**Comment by gansidui** [comment]
一般你的做法就够用了吧， 网络IO本身就是瓶颈。
下面这种方式或许可以充分利用IO资源：
server1 --> server2 这个过程建一个连接池，比如10个长连接，在上层通过一个SendAndRecv接口来使用这10个长连接，
``` go
SendAndRecv(writeData []byte, readData []byte) {
	// find a free-time connection
	// ...

	if (notFreeConn) {
		// waiting
	}
	else {
		// ...
		conn.write(writeData)
		conn.read(readData)
	}
}
```

**Comment by businiaowyf** [comment]
很感谢~我也觉得连接池的办法好一些
