### ISSUE TITLE
请问gotcp 框架的处理性能你有测试过吗？

### ISSUE THREAD

**Issue by slw2011** [gansidui/gotcp#16]
请问gotcp 框架的处理性能你有测试过吗？
安装下列两种情况，使用gotcp作为server端的处理性能大概是多少呢？
1.client---->gotcp_server  这种情况下的gotcp_server 的处理量是多少每秒？
2.client---->interface---->gotcp_server   这种情况下的gotcp_server 的处理量是多少每秒？

**Comment by gansidui** [comment]
没对比测试过，不过断言的耗时和IO相比可以忽略吧

**Comment by gansidui** [comment]
不需要极致性能，但求代码简单易懂，方便维护
