### ISSUE TITLE
ReadPacket只能一次返回一个包呀.

### ISSUE THREAD

**Issue by DrmagicE** [gansidui/gotcp#20]
如果是telnetprotol中的例子。考虑一个粘包问题：
客户端连续发送:
echo 123 [\r\n]
echo 456 [\r\n]

这个时候ReadPacket只能处理echo 123，echo 456就被丢弃了..

**Comment by gansidui** [comment]
可以修改TelnetProtocol的ReadPacket函数。从conn中每读取两个字节都判断一下是不是 \r\n，如果是就返回，这样剩余的数据依然在conn中可以供下次ReadPacket时使用

**Comment by DrmagicE** [comment]
有道理有道理..
