### ISSUE TITLE
关于waitgroup

### ISSUE THREAD

**Issue by ronalfei** [gansidui/gotcp#9]
我评论了这次commit
https://github.com/gansidui/gotcp/commit/bc20b14c0218de0d1369e9b1f3bec52660c36585

我觉得从代码维护性上来看,  如果一个goroutine需要Done, 那么应该在本函数Add, 这样不用分散的去找哪里add的.
这里有个讨论的帖子:
http://stackoverflow.com/questions/19208725/example-for-sync-waitgroup-correct

**Comment by gansidui** [comment]
是的，你说的没错，从维护者的角度来看，哪个地方调用Add就应该哪个地方调用Done。
```go
func asyncDo(fn func(), wg *sync.WaitGroup) {
	wg.Add(1)
	go func() {
		fn()
		wg.Done()
	}()
}
```
改成这种形式或许好一些

**Comment by ronalfei** [comment]
ok,我先关闭
